name: CDK Diff on Pull Request

on:
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/**'
      - 'app.py'
      - 'requirements.txt'
      - 'cdk.json'

env:
  AWS_REGION: us-east-1
  PYTHON_VERSION: '3.12'
  NODE_VERSION: '18'

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Synth
        run: |
          cdk synth --context environment=dev

      - name: CDK Diff against Dev
        id: cdk-diff-dev
        run: |
          echo "## 🔍 CDK Diff Results (Development)" >> diff_output.md
          echo "" >> diff_output.md
          echo "### Changes to be applied:" >> diff_output.md
          echo "" >> diff_output.md
          echo '```diff' >> diff_output.md
          cdk diff --context environment=dev >> diff_output.md 2>&1 || true
          echo '```' >> diff_output.md
          echo "" >> diff_output.md

      - name: CDK Security Check
        run: |
          echo "### 🔒 Security Analysis" >> diff_output.md
          echo "" >> diff_output.md
          
          # Check for potential security issues in CDK changes
          if cdk synth --context environment=dev | grep -i "publicread\|publicreadwrite\|public.*access"; then
            echo "⚠️ **WARNING**: Potential public access detected in resources!" >> diff_output.md
          else
            echo "✅ No obvious public access issues detected." >> diff_output.md
          fi
          echo "" >> diff_output.md

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const diffOutput = fs.readFileSync('diff_output.md', 'utf8');
            
            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const existingComment = comments.data.find(comment => 
              comment.body.includes('🔍 CDK Diff Results')
            );
            
            const commentBody = `${diffOutput}
            
---
*This diff was generated automatically for PR #${{ github.event.number }}*
*Last updated: ${new Date().toISOString()}*`;
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }